name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/black-check@master

  pytest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install

      - name: Downgrade soundfile version on macOS x86_64
        # soundfile>=0.12.0 prepackages libsndfile, but the prepackaged version gives
        # different results than the system version for macOS running x86_64
        # (which is what GitHub Actions uses). As such we have to downgrade to
        # soundfile==0.11.0 and use the system libsndfile.
        run: |
          if [ "$RUNNER_OS" == "macOS" ] && [ "$(uname -m)" == "x86_64" ]; then
            poetry add soundfile==0.11.0
          fi
        shell: bash

      - name: Test with pytest
        run: poetry run pytest --dist no -n 0
        env:
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}
